/**
 * JSON-LD Structured Data Components for SEO
 *
 * These components add schema.org structured data to help search engines
 * understand and display rich results for the application.
 */

const siteUrl = "https://docsversionhistory.com";
const siteName = "Docs Version History";
const siteDescription =
  "Add realistic version history to your Google Docs. Schedule text to appear gradually and create authentic document revision history.";

/**
 * WebSite Schema - Provides site-wide information
 * Helps with sitelinks search box and brand recognition
 */
export function WebsiteJsonLd() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: siteName,
    url: siteUrl,
    description: siteDescription,
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${siteUrl}/?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * SoftwareApplication Schema - Describes the app
 * Helps with rich snippets showing app info, ratings, pricing
 */
export function SoftwareAppJsonLd() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: siteName,
    description: siteDescription,
    url: siteUrl,
    applicationCategory: "ProductivityApplication",
    operatingSystem: "Web",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: "4.8",
      ratingCount: "150",
      bestRating: "5",
      worstRating: "1",
    },
    featureList: [
      "Google Docs version history creation",
      "Document revision tracking",
      "Scheduled text insertion",
      "Writing progress visualization",
      "AI content detection",
      "Text humanization",
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * Organization Schema - Company/brand information
 */
export function OrganizationJsonLd() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: siteName,
    url: siteUrl,
    logo: `${siteUrl}/logo.png`,
    sameAs: [],
    contactPoint: {
      "@type": "ContactPoint",
      email: "support@docsversionhistory.com",
      contactType: "customer support",
    },
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * FAQ Schema - For FAQ pages
 * Pass an array of {question, answer} objects
 */
export function FAQJsonLd({
  faqs,
}: {
  faqs: Array<{ question: string; answer: string }>;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * BreadcrumbList Schema - For page navigation
 */
export function BreadcrumbJsonLd({
  items,
}: {
  items: Array<{ name: string; url: string }>;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: item.url,
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * AI Detector FAQ Schema - Pre-built for the AI detector page
 */
export function AIDetectorFAQJsonLd() {
  const faqs = [
    {
      question: "How accurate is the AI content detector?",
      answer:
        "Our AI detector achieves 99% accuracy in identifying AI-generated content. It uses advanced machine learning models trained on millions of samples to distinguish between human and AI-written text.",
    },
    {
      question: "What AI models can the detector identify?",
      answer:
        "Our detector can identify content generated by ChatGPT (GPT-3.5, GPT-4), Claude, Bard, Jasper, and other major AI writing tools. We continuously update our models to detect the latest AI systems.",
    },
    {
      question: "Is my text stored when I use the AI detector?",
      answer:
        "No, your text is never stored. All analysis happens in real-time and your content is immediately discarded after processing. We prioritize your privacy and data security.",
    },
    {
      question: "How does the text humanization work?",
      answer:
        "Our humanization tool rewrites AI-generated content to sound more natural and human-like while preserving the original meaning. It adjusts sentence structure, word choice, and flow patterns.",
    },
    {
      question: "Is the AI detector free to use?",
      answer:
        "Yes! Our AI content detector and text humanizer are completely free to use. No account required, no credit card needed. Just paste your text and get instant results.",
    },
  ];

  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * Landing Page FAQ Schema - Generic FAQ for landing pages
 */
export function LandingPageFAQJsonLd({
  faqs,
}: {
  faqs: Array<{ question: string; answer: string }>;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * HowTo Schema - For step-by-step instructions
 */
export function HowToJsonLd({
  name,
  description,
  steps,
}: {
  name: string;
  description: string;
  steps: Array<{ name: string; text: string }>;
}) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    description,
    step: steps.map((step, index) => ({
      "@type": "HowToStep",
      position: index + 1,
      name: step.name,
      text: step.text,
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

/**
 * Homepage FAQ Schema - Pre-built for the landing page
 */
export function HomepageFAQJsonLd() {
  const faqs = [
    {
      question: "What is Google Docs version history?",
      answer:
        "Google Docs version history is a feature that automatically tracks every change made to a document. It shows who made changes, when they were made, and allows you to restore previous versions. Our tool helps you create authentic version history by gradually inserting text over time.",
    },
    {
      question: "How does the document version tracking work?",
      answer:
        "You paste or upload your text, choose a duration (from 30 minutes to 1 week), and our tool gradually adds the content into a new Google Doc sentence by sentence. This creates a realistic revision history that shows your document being written over time.",
    },
    {
      question: "Can I track changes in my existing Google Docs?",
      answer:
        "Our tool creates new Google Docs with built-in version history. You can then use Google's native version history feature to see exactly how and when each part of your document was added.",
    },
    {
      question: "Is the AI content detector accurate?",
      answer:
        "Yes, our AI detector achieves 99% accuracy in identifying AI-generated content. It provides sentence-level highlighting so you can see exactly which parts of your text may be flagged as machine-written.",
    },
    {
      question: "Is Docs Version History free to use?",
      answer:
        "Yes! Our document history tool is completely free. No credit card required. Just sign in with your Google account and start creating version history for your documents.",
    },
  ];

  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}
